version = 1

test_patterns = ["*/test/**"]

exclude_patterns = ["examples/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser"
  ]
  module_system = "es-modules"
